---
label: Project
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
  description: test
  hidden: false
- name: lang
  type: select
  default: []
  config:
    required: false
    options:
    - es
    - en
    source:
      type: simple
      section: 
      file: 
      path: 
  label: lang
- name: image
  type: file
  config:
    maxSize: 64
  label: image
pages:
- content/projects/en/prueba.md
- content/projects/es/prueba.md
